# I am unsure of what others think of yaml,
# I think it's more compact and nice. -Fred
server:
  port: 9099
spring:
  datasource:
    url: jdbc:h2:file:./myTestH2Folder/myTestH2file
    username: sa
    password: mypass
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations:
      - classpath:./testdata.sql
      mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration 

# Code for setting up email capabilities through spring
# Currently set for gmail, but we can change that or not, its whatever we wanna do.
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      
document:
  bucket-name: avatarimages2005
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: ${AWS_S3_KEY}
      secret-key: ${AWS_S3_SKEY}
      
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

